# Generated by Django 4.2.6 on 2025-08-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_notification'),
    ]

    operations = [
    ]
