# Generated by Django 4.2.6 on 2025-08-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20250825_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
