# Generated by Django 4.2.6 on 2025-01-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_custommeal_ingredient_unit_based_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommeal',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='custommeal',
            name='meal_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='custommeal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meals', to='nutrition.plan'),
        ),
    ]
