# Generated by Django 4.2.6 on 2025-05-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_custommeal_day_custommeal_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommealingredient',
            name='custom_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='nutrition.custommeal'),
        ),
    ]
