# Generated by Django 4.2.6 on 2025-05-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_regularusermeasurement'),
        ('nutrition', '0006_alter_custommealingredient_custom_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativeMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ComparativePlanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tabla comparativa', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparative_plan_tables', to='user.regularuser')),
            ],
        ),
        migrations.CreateModel(
            name='ComparativePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plan', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparative_plans', to='nutrition.comparativeplantable')),
            ],
        ),
        migrations.CreateModel(
            name='ComparativeMealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(default='g', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='nutrition.comparativemeal')),
            ],
        ),
        migrations.AddField(
            model_name='comparativemeal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.comparativeplan'),
        ),
    ]
